# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Atharv.
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Configuration
server.port=8080

spring.web.resources.static-locations=classpath:/static/

# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin

# Thymeleaf Configuration
spring.thymeleaf.cache=false

logging.level.com.example.ecommerce=DEBUG
logging.file.name=ecommerce.log

# Email Configuration (OTP 2FA)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=team.shopease@gmail.com
spring.mail.password=kjxm eyzv ypht yehr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Encryption Configuration
# The key will be generated automatically if not provided
# For production, generate a secure key and set it here
app.encryption.key=Wh6AdZAn06T2x9a0KZaaSrn2ZiVG8anymeUcLL0W61c=
